---
general:
  author: am c00l pl0x#7196
  creation_date: 2/28/2021
  version: "1.5"
  notes: whoever reads this just lost the game
  source_code: https://github.com/zainthemaynnn/zlave

client: ~ # all generated in info.py